server:
  port: 8091

spring:
  application:
    name: game-analyse
  datasource:
    url: jdbc:mysql://localhost:3306/club_liaoning?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true