eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club_liaoning?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  application:
    name: admin-check